version: '2'
services:
  employee-time-tracker:
    container_name: employee-time-tracker
    build:
      context: .
      dockerfile: Dockerfile
    image: balajiabgs/employee-timetracker:#{Build.BuildId}#
    environment:
      TIMETRACKERURL: 'http://timetracker:8080'
    expose:
      - 8081
    ports:
      - 8081:8080
    links:
      - timetracker:timetracker
    depends_on:
      - timetracker
  timetracker:
    container_name: timetracker
    image: alirizasaral/timetracker:1
    expose:
      - 8080
    ports:
      - 8080:8080
